//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiaoBodan
    {
        public int MoveNo { get; set; }
        public string WareOutID { get; set; }
        public System.DateTime MoveDate { get; set; }
        public string WareID { get; set; }
        public string MareName { get; set; }
        public string Permitter { get; set; }
        public string Udef1 { get; set; }
        public string Udef2 { get; set; }
        public string Remark { get; set; }
        public string ShenHe { get; set; }
        public string ShenHeren { get; set; }
        public string ShenHetime { get; set; }
        public string One { get; set; }
    }
}
