//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiaoBodanXB
    {
        public int SerNo { get; set; }
        public string ProdID { get; set; }
        public string PrrodName { get; set; }
        public string ProdSize { get; set; }
        public string Unit { get; set; }
        public string Quantity { get; set; }
        public string HaveBatch { get; set; }
        public string ItemRemark { get; set; }
        public string One { get; set; }
    }
}
