//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PandiandanXB
    {
        public int SerNo { get; set; }
        public int ProdID { get; set; }
        public string ProdName { get; set; }
        public string PordSize { get; set; }
        public string Unit { get; set; }
        public int CurQty { get; set; }
        public int CheckQty { get; set; }
        public int Quantity { get; set; }
        public double Price { get; set; }
        public int Amount { get; set; }
        public int HaveBatch { get; set; }
        public string ItemRemark { get; set; }
        public string one { get; set; }
    }
}
