//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_bei
    {
        public int Cplumn { get; set; }
        public string Single { get; set; }
        public string SingleDate { get; set; }
        public string OddNumber { get; set; }
        public string Lnvoice { get; set; }
        public string Transactio { get; set; }
        public string NameTransaction { get; set; }
        public string Department { get; set; }
        public string DepartmentName { get; set; }
        public string Purchasing { get; set; }
        public string EntryName { get; set; }
        public string Currency { get; set; }
        public string Exchange { get; set; }
        public string Money { get; set; }
        public string Summ { get; set; }
        public string Zhirsum { get; set; }
        public string CkuanSum { get; set; }
        public string CdiSum { get; set; }
        public string Ccc { get; set; }
    }
}
