//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_CaiGouFengTanJG
    {
        public int BillDate { get; set; }
        public Nullable<int> CaiGouRKID { get; set; }
        public string WUliaoBH { get; set; }
        public string WUliaoName { get; set; }
        public string GuiGeXH { get; set; }
        public string CaiGouJE { get; set; }
        public Nullable<int> ShuLiang { get; set; }
        public Nullable<int> DanWei { get; set; }
        public Nullable<int> ZhongLiang { get; set; }
        public Nullable<int> CaiJi { get; set; }
        public string FengTanJE { get; set; }
        public string a { get; set; }
        public string b { get; set; }
    }
}
