//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_CaiGouTuiHuo
    {
        public string CustName { get; set; }
        public string BillDate { get; set; }
        public string AddrID { get; set; }
        public string CustAddress { get; set; }
        public int BillNo { get; set; }
        public string CurrID { get; set; }
        public string PriceofTax { get; set; }
        public string ExchRate { get; set; }
        public string WareName { get; set; }
        public string HasForeignTrade { get; set; }
        public string IsDeduct { get; set; }
        public string SelesName { get; set; }
        public string Maker { get; set; }
        public string DepartName { get; set; }
        public string Permitter { get; set; }
        public string ProjectName { get; set; }
        public string UDef1 { get; set; }
        public string UDef2 { get; set; }
        public string Remark { get; set; }
        public string a { get; set; }
        public string b { get; set; }
    }
}
