//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_fapiao
    {
        public int Supplier { get; set; }
        public string BillDate { get; set; }
        public int BillHaoma { get; set; }
        public string BillType { get; set; }
        public string FapiaoHoma { get; set; }
        public string Caig { get; set; }
        public string FapiaoType { get; set; }
        public string Pingzhengbianhao { get; set; }
        public string Bibie { get; set; }
        public string Chajiabianhao { get; set; }
        public string Huilv { get; set; }
        public string Caigrengyuan { get; set; }
        public string Zhidanrengyuan { get; set; }
        public string Staff { get; set; }
        public string Item { get; set; }
        public string Reviewer { get; set; }
        public string Customone { get; set; }
        public string Customtwo { get; set; }
        public string Remarks { get; set; }
        public string DddHoma { get; set; }
    }
}
