//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_qingdan
    {
        public int Cplumn { get; set; }
        public string Wuliaobianh { get; set; }
        public string Wuliaomcheng { get; set; }
        public string Type { get; set; }
        public string Danwei { get; set; }
        public string Danjia { get; set; }
        public string Jine { get; set; }
        public string Number { get; set; }
        public string Danj { get; set; }
        public string Je { get; set; }
        public string Shuilv { get; set; }
        public string Shuie { get; set; }
        public string Hanshuije { get; set; }
        public string Huicha { get; set; }
        public string Jiacha { get; set; }
        public string Jiacbengweibi { get; set; }
        public string Chaeheji { get; set; }
        public string Laiyuandanbie { get; set; }
        public string Laiyuandanhao { get; set; }
        public string Ttt { get; set; }
    }
}
