//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class yingshouchongkuanqyy
    {
        public string OffsetNo { get; set; }
        public string OriginFlag { get; set; }
        public string FromOrderNo { get; set; }
        public double PrepayLeft { get; set; }
        public string DeptID { get; set; }
        public string DeptName { get; set; }
        public double UseMoney { get; set; }
        public string FromDescription { get; set; }
        public string a { get; set; }
        public string b { get; set; }
        public string c { get; set; }
    }
}
