//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class yingshouchongkuanneirong
    {
        public int SerNo { get; set; }
        public string OriginFlag { get; set; }
        public System.DateTime OriginBilldate { get; set; }
        public string OriginBillNo { get; set; }
        public string InvoiceNo { get; set; }
        public int CustID { get; set; }
        public string CustName { get; set; }
        public int DeptID { get; set; }
        public string DeptName { get; set; }
        public string PersonName { get; set; }
        public string ProjectName { get; set; }
        public int CurrID { get; set; }
        public double ExchRate { get; set; }
        public double Total { get; set; }
        public double NowLeft { get; set; }
        public double Discount { get; set; }
        public double Offset { get; set; }
        public double OffsetMoney { get; set; }
        public string a { get; set; }
        public string b { get; set; }
        public string c { get; set; }
    }
}
