//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class cangku
    {
        public int WareHouseID { get; set; }
        public string WareHouseName { get; set; }
        public string ShortName { get; set; }
        public string EngName { get; set; }
        public string LinkMan { get; set; }
        public int Telephone { get; set; }
        public string WareHouseAddress { get; set; }
        public string Memo { get; set; }
        public string one { get; set; }
    }
}
