//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class cgqgdnr
    {
        public int StuNo { get; set; }
        public string ProdID { get; set; }
        public string ProdName { get; set; }
        public string ProdSize { get; set; }
        public string SUnit { get; set; }
        public string sQuantity { get; set; }
        public string CurrID { get; set; }
        public Nullable<float> sPrice { get; set; }
        public Nullable<float> Amount { get; set; }
        public Nullable<float> LastestsPrice { get; set; }
        public Nullable<float> LastestAmount { get; set; }
        public Nullable<System.DateTime> PreInDate { get; set; }
        public Nullable<System.DateTime> SuggestPur { get; set; }
        public Nullable<int> QtyRemain { get; set; }
        public string ItemRemark { get; set; }
        public string TranType { get; set; }
        public Nullable<int> FromNo { get; set; }
        public string a { get; set; }
        public string b { get; set; }
    }
}
