//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class cgxjd
    {
        public string CustomerID { get; set; }
        public string AddressID { get; set; }
        public Nullable<System.DateTime> ValidDate { get; set; }
        public Nullable<System.DateTime> PriceOfTax { get; set; }
        public string BillDate { get; set; }
        public string BillNO { get; set; }
        public string CurrID { get; set; }
        public Nullable<double> ExchRate { get; set; }
        public string OutAddress { get; set; }
        public string Maker { get; set; }
        public string SalesName { get; set; }
        public string Permitter { get; set; }
        public string DepartID { get; set; }
        public string a { get; set; }
        public string b { get; set; }
    }
}
