//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeHuZB
    {
        public string rybh { get; set; }
        public System.DateTime ssbm { get; set; }
        public string ryxm { get; set; }
        public string ywxm { get; set; }
        public string sfzh { get; set; }
        public string rzsj { get; set; }
        public string zzrq { get; set; }
        public string syqc { get; set; }
        public string gj { get; set; }
        public string ldrq { get; set; }
        public string jszw { get; set; }
        public string zwzw { get; set; }
        public string ywzw { get; set; }
        public string lxyb { get; set; }
        public string lxdz { get; set; }
        public string lxdh { get; set; }
    }
}
