//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class erpEntities : DbContext
    {
        public erpEntities()
            : base("name=erpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<bumenweihu> bumenweihu { get; set; }
        public DbSet<bz> bz { get; set; }
        public DbSet<cangku> cangku { get; set; }
        public DbSet<cgdd> cgdd { get; set; }
        public DbSet<cgddnr> cgddnr { get; set; }
        public DbSet<cgqgd> cgqgd { get; set; }
        public DbSet<cgqgdnr> cgqgdnr { get; set; }
        public DbSet<cgxjd> cgxjd { get; set; }
        public DbSet<diaobodan> diaobodan { get; set; }
        public DbSet<diaobodanxb> diaobodanxb { get; set; }
        public DbSet<kucundaizhi> kucundaizhi { get; set; }
        public DbSet<kucuntaizhang> kucuntaizhang { get; set; }
        public DbSet<mingxikehu> mingxikehu { get; set; }
        public DbSet<mingxiyewuyuan> mingxiyewuyuan { get; set; }
        public DbSet<pandiandan> pandiandan { get; set; }
        public DbSet<pandiandanxb> pandiandanxb { get; set; }
        public DbSet<qitaruku> qitaruku { get; set; }
        public DbSet<qitarukuxiang> qitarukuxiang { get; set; }
        public DbSet<quotation> quotation { get; set; }
        public DbSet<quotaxiang> quotaxiang { get; set; }
        public DbSet<renyuanweihu> renyuanweihu { get; set; }
        public DbSet<tb_caigoufengtan> tb_caigoufengtan { get; set; }
        public DbSet<tb_caigoufengtanjg> tb_caigoufengtanjg { get; set; }
        public DbSet<tb_caigoufengtanmx> tb_caigoufengtanmx { get; set; }
        public DbSet<tb_caigourukud> tb_caigourukud { get; set; }
        public DbSet<tb_caigourukudneir> tb_caigourukudneir { get; set; }
        public DbSet<tb_caigoutuihuo> tb_caigoutuihuo { get; set; }
        public DbSet<tb_caigoutuihuotwo> tb_caigoutuihuotwo { get; set; }
        public DbSet<tb_wuliaoweihu> tb_wuliaoweihu { get; set; }
        public DbSet<tb_wuliaoweihucunliangxx> tb_wuliaoweihucunliangxx { get; set; }
        public DbSet<tb_wuliaoweihujbziliao> tb_wuliaoweihujbziliao { get; set; }
        public DbSet<tb_wuliaoweihujyziliao> tb_wuliaoweihujyziliao { get; set; }
        public DbSet<tiaojiadanxb> tiaojiadanxb { get; set; }
        public DbSet<tuihuo> tuihuo { get; set; }
        public DbSet<tuihuoneirong> tuihuoneirong { get; set; }
        public DbSet<weihubiao> weihubiao { get; set; }
        public DbSet<xiaoshoudingd> xiaoshoudingd { get; set; }
        public DbSet<xiaoshoufabiao> xiaoshoufabiao { get; set; }
        public DbSet<xiaoshoufabiaoneirong> xiaoshoufabiaoneirong { get; set; }
        public DbSet<xiaoshoufabiaoqingdan> xiaoshoufabiaoqingdan { get; set; }
        public DbSet<xiaoshouzhi> xiaoshouzhi { get; set; }
        public DbSet<yingshouchongkuan> yingshouchongkuan { get; set; }
        public DbSet<yingshouchongkuanneirong> yingshouchongkuanneirong { get; set; }
        public DbSet<yingshouchongkuanqyys> yingshouchongkuanqyys { get; set; }
        public DbSet<yingshoukuan> yingshoukuan { get; set; }
        public DbSet<yingshoukuanxiangbiao> yingshoukuanxiangbiao { get; set; }
        public DbSet<tiaojiadan> tiaojiadan { get; set; }
    }
}
