//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class qitaruku
    {
        public string BillStyeID { get; set; }
        public Nullable<System.DateTime> AdjustDate { get; set; }
        public string WareID { get; set; }
        public string BillNo { get; set; }
        public string VoucherNO { get; set; }
        public string SalesID { get; set; }
        public string Maker { get; set; }
        public string DepartID { get; set; }
        public string Permitter { get; set; }
    }
}
