//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RenyuanWeihu
    {
        public int PersonID { get; set; }
        public string DepartID { get; set; }
        public string PersonName { get; set; }
        public string Sex { get; set; }
        public string EngName { get; set; }
        public Nullable<int> Idcard { get; set; }
        public string Birthday { get; set; }
        public string Polity { get; set; }
        public string Hyzk { get; set; }
        public Nullable<System.DateTime> RZRQ { get; set; }
        public string XueX { get; set; }
        public Nullable<System.DateTime> ZZtime { get; set; }
        public string JG { get; set; }
        public string Shiyongqz { get; set; }
        public string Guoji { get; set; }
        public Nullable<System.DateTime> Lizhitime { get; set; }
        public string MingZu { get; set; }
        public string JishuZZ { get; set; }
        public string ZhongwenZZ { get; set; }
        public string YingwneZZ { get; set; }
        public string LianxiYB { get; set; }
        public string LianxiDZ { get; set; }
        public string LianxiDH { get; set; }
        public string YidongDH { get; set; }
        public string ZuigaoXL { get; set; }
        public Nullable<System.DateTime> Daozhitime { get; set; }
        public string XueWei { get; set; }
        public string Rujintime { get; set; }
        public string BiyeXX { get; set; }
        public string HuzhaoHM { get; set; }
        public string SuoXueZY { get; set; }
        public Nullable<System.DateTime> Hetongqishitime { get; set; }
        public Nullable<System.DateTime> Hetongzhongzhitime { get; set; }
        public string WaiyuSP { get; set; }
        public string Tijiantime { get; set; }
        public string HetongQi { get; set; }
        public string DianziYJ { get; set; }
        public string XianDH { get; set; }
        public string HujiDH { get; set; }
        public string XianYB { get; set; }
        public string HujiYB { get; set; }
        public string XianZZ { get; set; }
        public string HujiDZ { get; set; }
        public string JinjiLXR { get; set; }
        public string JiatingDH { get; set; }
        public string JinjiLXYB { get; set; }
        public string JiatingYB { get; set; }
        public string JinjiLXDH { get; set; }
        public string JiatingZZ { get; set; }
        public string JinjiLXDZ { get; set; }
        public string ZDLY { get; set; }
        public string ZDLE { get; set; }
        public string ZDLS { get; set; }
        public string ZDLSi { get; set; }
        public string ZDW { get; set; }
        public string ZDLL { get; set; }
        public string BeiZhu { get; set; }
        public string one { get; set; }
    }
}
