//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_store
    {
        public int Supplier { get; set; }
        public string BillDate { get; set; }
        public string a { get; set; }
        public string b { get; set; }
        public string c { get; set; }
        public string BillHaoma { get; set; }
        public string Bibie { get; set; }
        public string HuiLv { get; set; }
        public string Zhikoulv { get; set; }
        public string Type { get; set; }
        public string Month { get; set; }
        public string Number { get; set; }
        public string Department { get; set; }
        public string Staff { get; set; }
        public string Item { get; set; }
        public string Reviewer { get; set; }
        public string Customone { get; set; }
        public string Customtwo { get; set; }
        public string Remarks { get; set; }
        public string Bbb { get; set; }
    }
}
