//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_CaiGouRuKuDNeiR
    {
        public int SerNo { get; set; }
        public Nullable<int> ProdID { get; set; }
        public string ProdName { get; set; }
        public string ProdSize { get; set; }
        public string SUnit { get; set; }
        public Nullable<int> SQuantity { get; set; }
        public string OldPrice { get; set; }
        public string Discount { get; set; }
        public string SPrice { get; set; }
        public string Amount { get; set; }
        public string TaxRate { get; set; }
        public string TaxAmt { get; set; }
        public string AmountATax { get; set; }
        public string HaveBetch { get; set; }
        public string IsGift { get; set; }
        public string HasInv { get; set; }
        public Nullable<int> HotInvCount { get; set; }
        public string ItemRemark { get; set; }
        public string TranType { get; set; }
        public string FromNO { get; set; }
        public string MLAppFare { get; set; }
        public string a { get; set; }
        public string b { get; set; }
    }
}
