//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_caigoufengtanmx
    {
        public int BillDate { get; set; }
        public Nullable<int> FeiYongID { get; set; }
        public string FeiYongName { get; set; }
        public string CurrID { get; set; }
        public Nullable<float> ExchRate { get; set; }
        public Nullable<float> Amount { get; set; }
        public Nullable<float> LocalAmount { get; set; }
        public string a { get; set; }
        public string b { get; set; }
    }
}
