//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_wuliaoweihucunliangxx
    {
        public int SafeQty { get; set; }
        public Nullable<int> CSafeAllStk { get; set; }
        public Nullable<int> BAllAmt { get; set; }
        public Nullable<int> CAllAmt { get; set; }
        public Nullable<double> BAvgCost { get; set; }
        public Nullable<double> CAvgCost { get; set; }
        public Nullable<double> BStdCost { get; set; }
        public Nullable<double> CStdCost { get; set; }
        public Nullable<double> BTotalCost { get; set; }
        public Nullable<double> XXzongCBCost { get; set; }
        public string a { get; set; }
        public string b { get; set; }
    }
}
