//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_WuLiaoWeiHuCunLiangXX
    {
        public Nullable<int> SafeQty { get; set; }
        public Nullable<int> CSafeAllStk { get; set; }
        public Nullable<int> BAllAmt { get; set; }
        public Nullable<int> CAllAmt { get; set; }
        public string BAvgCost { get; set; }
        public string CAvgCost { get; set; }
        public string BStdCost { get; set; }
        public string CStdCost { get; set; }
        public string BTotalCost { get; set; }
        public string XXzongCBCost { get; set; }
        public string a { get; set; }
        public string b { get; set; }
    }
}
