//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_wuliaoweihujbziliao
    {
        public double SuggestPrice { get; set; }
        public string CurrName { get; set; }
        public Nullable<double> SalesPriceA { get; set; }
        public Nullable<double> SalesPriceB { get; set; }
        public Nullable<double> SalesPriceC { get; set; }
        public Nullable<double> SalesPriceD { get; set; }
        public Nullable<double> SalesPriceE { get; set; }
        public Nullable<double> StdPrice { get; set; }
        public string ProdForm { get; set; }
        public string PriceOfTax { get; set; }
        public string TaxItemsID { get; set; }
        public Nullable<double> BusiTaxRate { get; set; }
        public Nullable<int> AdvanceDays { get; set; }
        public string MajorSupplier { get; set; }
        public string a { get; set; }
        public string b { get; set; }
    }
}
