//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_WuLiaoWeiHuJYziliao
    {
        public Nullable<System.DateTime> ZCchukuR { get; set; }
        public Nullable<System.DateTime> BQutStockDay { get; set; }
        public Nullable<System.DateTime> BInStockDay { get; set; }
        public Nullable<System.DateTime> ZJrukuDate { get; set; }
        public Nullable<int> SluggishDays { get; set; }
        public Nullable<System.DateTime> InvalidDate { get; set; }
        public string a { get; set; }
        public string b { get; set; }
    }
}
