//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_WuLiaoWeiHu
    {
        public int ProdID { get; set; }
        public string Classleibie { get; set; }
        public string ClassName { get; set; }
        public string StdUnitName { get; set; }
        public string ProdSize { get; set; }
        public Nullable<int> BarCodeID { get; set; }
        public string EngName { get; set; }
        public string BatchUsed { get; set; }
        public string EffectDateUsed { get; set; }
        public string ValidDateUsed { get; set; }
        public string DefValidDay { get; set; }
        public string UDef1 { get; set; }
        public string UDef2 { get; set; }
        public string Remark { get; set; }
        public string a { get; set; }
        public string b { get; set; }
    }
}
