//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH
    {
        public string CustID { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public string SoHuoAddress { get; set; }
        public Nullable<int> BillNo { get; set; }
        public string YesNoshui { get; set; }
        public string BB { get; set; }
        public string Cangku { get; set; }
        public string Huilv { get; set; }
        public string Chongxingchuku { get; set; }
        public string Guowaimaoyi { get; set; }
        public Nullable<int> Pingzhengbianhao { get; set; }
        public string Yewurenyuan { get; set; }
        public string Zhidanrenyuan { get; set; }
        public string Suoshubumen { get; set; }
        public string Fuherenyuan { get; set; }
        public string Suoshuxiangmu { get; set; }
        public string one { get; set; }
    }
}
