//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class thnr
    {
        public string Lanmu { get; set; }
        public Nullable<int> Wuliaobianhao { get; set; }
        public string Wuliaomingcheng { get; set; }
        public string Guigexinghao { get; set; }
        public string Danweimingcheng { get; set; }
        public Nullable<int> Shuliang { get; set; }
        public Nullable<int> Zhekouqiandanjia { get; set; }
        public Nullable<int> Zheshu { get; set; }
        public Nullable<int> Danjia { get; set; }
        public Nullable<int> Jine { get; set; }
        public Nullable<int> Shuilv { get; set; }
        public Nullable<int> Hanshuijine { get; set; }
        public Nullable<int> Pihao { get; set; }
        public string Zengping { get; set; }
        public string Fapiaomingxi { get; set; }
        public Nullable<int> Weikaipiaoshuliang { get; set; }
        public string Fenlubeizhu { get; set; }
        public string Laiyuandanbie { get; set; }
        public Nullable<int> Laiyuandanhao { get; set; }
        public string one { get; set; }
    }
}
