//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tiaojiadan
    {
        public int BillNo { get; set; }
        public System.DateTime AdjustDate { get; set; }
        public string IncSubjectID { get; set; }
        public string VoucherNo { get; set; }
        public string DecSujectID { get; set; }
        public string Tiaozheng { get; set; }
        public string Maker { get; set; }
        public string Permitter { get; set; }
        public string UDef1 { get; set; }
        public string UDf2 { get; set; }
        public string ShenHe { get; set; }
        public string ShenHeren { get; set; }
        public string ShenHetime { get; set; }
        public string a { get; set; }
    }
}
