//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tuihuoneirong
    {
        public string Lanmu { get; set; }
        public int Wuliaobianhao { get; set; }
        public string Wuliaomingcheng { get; set; }
        public string Guigexinghao { get; set; }
        public string Danweimingcheng { get; set; }
        public int Shuliang { get; set; }
        public int Zhekouqiandanjia { get; set; }
        public int Zheshu { get; set; }
        public int Danjia { get; set; }
        public int Jine { get; set; }
        public int Shuilv { get; set; }
        public int Hanshuijine { get; set; }
        public int Pihao { get; set; }
        public string Zengping { get; set; }
        public string Fapiaomingxi { get; set; }
        public int Weikaipiaoshuliang { get; set; }
        public string Fenlubeizhu { get; set; }
        public string Laiyuandanbie { get; set; }
        public int Laiyuandanhao { get; set; }
        public string one { get; set; }
    }
}
