//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Xiaoshoudingd
    {
        public string BillNO { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public string FormalCust { get; set; }
        public string CustomerID { get; set; }
        public string CustAreaID { get; set; }
        public string CustAreaName { get; set; }
        public Nullable<System.DateTime> ValidDate { get; set; }
        public Nullable<double> PriceOfTax { get; set; }
        public string CustBillNo { get; set; }
        public string BillStatus { get; set; }
        public string CurrID { get; set; }
        public string ExchRate { get; set; }
        public string SalesID { get; set; }
        public string Rermitter { get; set; }
        public string DepartID { get; set; }
        public string Permitter { get; set; }
        public string Beiyong { get; set; }
    }
}
