//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class xiaoshoufabiaoqingdan
    {
        public int SerNo { get; set; }
        public string ProdId { get; set; }
        public string ProdName { get; set; }
        public string ProdSize { get; set; }
        public string SUnit { get; set; }
        public Nullable<float> SourcePrice { get; set; }
        public float Amount { get; set; }
        public int SQuantity { get; set; }
        public int HasCombine { get; set; }
        public float Price { get; set; }
        public float Amountaa { get; set; }
        public float TaxRate { get; set; }
        public float TaxAmt { get; set; }
        public float AmountWithTax { get; set; }
        public string SourceType { get; set; }
        public string CustBillNo { get; set; }
        public int IsGift { get; set; }
        public string Remark { get; set; }
        public string a { get; set; }
        public string b { get; set; }
        public string c { get; set; }
    }
}
