//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class XiaoShouChuKan
    {
        public string kh { get; set; }
        public System.DateTime djrq { get; set; }
        public string shdz { get; set; }
        public string djhm { get; set; }
        public string xschlx { get; set; }
        public string bb { get; set; }
        public string hl { get; set; }
        public string ck { get; set; }
        public string gwmy { get; set; }
        public string pzbh { get; set; }
        public string cgry { get; set; }
        public string ssbm { get; set; }
        public string fhry { get; set; }
        public string shxm { get; set; }
    }
}
