//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class xiaoshoufabiao
    {
        public string CustID { get; set; }
        public int BillType { get; set; }
        public int PriceOfTax { get; set; }
        public string Addr { get; set; }
        public string AffirmState { get; set; }
        public string SrNo { get; set; }
        public string CVoucherNO { get; set; }
        public System.DateTime BillDate { get; set; }
        public string FundBillNo { get; set; }
        public string InvoiceNo { get; set; }
        public int InvoTypeId { get; set; }
        public int CurrID { get; set; }
        public float ExchRate { get; set; }
        public string Salesman { get; set; }
        public int DeptID { get; set; }
        public string ProjectID { get; set; }
        public string Maker { get; set; }
        public string Permitter { get; set; }
        public Nullable<int> a { get; set; }
        public string b { get; set; }
    }
}
