//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class yingshouchongkuan
    {
        public int CustomerID { get; set; }
        public string Jiesuanone { get; set; }
        public string Jiesuantwo { get; set; }
        public string Jiesuanthree { get; set; }
        public double DiscountPer { get; set; }
        public System.DateTime AccMonthToMonth { get; set; }
        public double BillDate { get; set; }
        public string FundBillNo { get; set; }
        public int CurrID { get; set; }
        public string OffSetStyle { get; set; }
        public string VoucherNo { get; set; }
        public int DeptID { get; set; }
        public string ProjectID { get; set; }
        public string Maker { get; set; }
        public string Permitter { get; set; }
        public string a { get; set; }
        public string b { get; set; }
        public string c { get; set; }
    }
}
