//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class yingshoukuan
    {
        public string Kehu { get; set; }
        public System.DateTime Danjuriqi { get; set; }
        public string Jiesuanyi { get; set; }
        public string Danjuhaoma { get; set; }
        public string Jiesuaner { get; set; }
        public string Bb { get; set; }
        public string Jiesuansan { get; set; }
        public int Huilv { get; set; }
        public int Zhekoulv { get; set; }
        public string Yingshouchongkuanleixing { get; set; }
        public System.DateTime Zhongzhizhangyue { get; set; }
        public string Pingzhengbianhao { get; set; }
        public string Suoshubumen { get; set; }
        public string Zhidanrenyuan { get; set; }
        public string Suoshuxiangmu { get; set; }
        public string Fuherenyuan { get; set; }
        public System.DateTime Shenheshijian { get; set; }
        public string Shenhezhuangtai { get; set; }
        public string one { get; set; }
    }
}
