//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class yingshoukuanxiangbiao
    {
        public int Lanhao { get; set; }
        public int Danbie { get; set; }
        public System.DateTime Yuandanriqi { get; set; }
        public int Yuandandanhao { get; set; }
        public int Fapiaohaoma { get; set; }
        public int Jiaoyiduixiang { get; set; }
        public string Jiaoyiduixiangmingcheng { get; set; }
        public int Bumenbianhao { get; set; }
        public string Bumenmingcheng { get; set; }
        public string Yewurenyuan { get; set; }
        public string Xiangmumingcheng { get; set; }
        public string Bibie { get; set; }
        public int Huilv { get; set; }
        public int Yuandanjine { get; set; }
        public int Xianxinyuane { get; set; }
        public int Zherangyue { get; set; }
        public int Chongkuanjine { get; set; }
        public int Chongdijin { get; set; }
        public string one { get; set; }
    }
}
