//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class yskxb
    {
        public int Lanhao { get; set; }
        public Nullable<int> Danbie { get; set; }
        public Nullable<System.DateTime> Yuandanriqi { get; set; }
        public Nullable<int> Yuandandanhao { get; set; }
        public Nullable<int> Fapiaohaoma { get; set; }
        public Nullable<int> Jiaoyiduixiang { get; set; }
        public string Jiaoyiduixiangmingcheng { get; set; }
        public Nullable<int> Bumenbianhao { get; set; }
        public string Bumenmingcheng { get; set; }
        public string Yewurenyuan { get; set; }
        public string Xiangmumingcheng { get; set; }
        public string Bibie { get; set; }
        public Nullable<int> Huilv { get; set; }
        public Nullable<int> Yuandanjine { get; set; }
        public Nullable<int> Xianxinyuane { get; set; }
        public Nullable<int> Zherangyue { get; set; }
        public Nullable<int> Chongkuanjine { get; set; }
        public Nullable<int> Chongdijin { get; set; }
        public string one { get; set; }
    }
}
